### ISSUE TITLE
*TRACKER* Shopping Cart

### ISSUE THREAD

**Issue by Michael-Sjogren** [dotnet-webshop/OrigamiShopFrontend#3]
- [x] dotnet-webshop/webshop#66
- [x] dotnet-webshop/webshop#65
- [x] dotnet-webshop/webshop#51
- [x] dotnet-webshop/webshop#64
- [x] dotnet-webshop/OrigamiShopFrontend#2
- [x] #12
