### ISSUE TITLE
*TRACKER* Customer user profile page

### ISSUE THREAD

**Issue by Michael-Sjogren** [dotnet-webshop/OrigamiShopFrontend#4]
a profile page for a customer
- [x] Create react component called CustomerProfile
- [x] Display data about customer , look for references of how a profile page looks like from other websites.
- [x] dotnet-webshop/webshop#59
